aggregator_site/aggregator_site/urls.py
from django.contrib import admin
from django.urls import path, include
from favorites.urls import router as favorites_router
from categories.urls import router as categories_router
from rest_framework_swagger.views import get_swagger_view


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("products.urls")),
    path("user/", include("users.urls")),
    path("favorites/", include("favorites.urls")),
    path("categories/", include("categories.urls")),
    path("spiders/", include("spiders.urls")),

    path('accounts/', include('allauth.urls')),

    path("api/favorites/", include(favorites_router.urls)),
    path("api/categories/", include(categories_router.urls)),
    path("api/products/", include("products.api_urls")),
    path("api/spiders/", include("spiders.api_urls")),
    path("api/", include("users.register_authorization_urls")),

    path('swagger/', get_swagger_view(title='API')),
]

admin.site.site_header = "Admin"

aggregator_site/favorites/urls.py
from django.urls import path, include
from . import api_views, views
from rest_framework.routers import DefaultRouter

app_name = "favorites"

router = DefaultRouter()
router.register(r"", api_views.FavoriteViewSet, basename="favorite")

urlpatterns = [
    path("", views.FavoriteList.as_view(), name="favorites_list"),
]

aggregator_site/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("sign-in/", views.UserAuthentication.as_view(), name="sign_in"),
    path("sign-out/", views.UserLogout.as_view(), name="sign_out"),
    path("registration/", views.UserCreate.as_view(), name="registration"),
    path("verify/<str:uuid>/", views.VerifyEmail.as_view(), name="verify_email"),
]

aggregator_site/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="UA-en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Hotprice</title>
  <link rel="shortcut icon" href="{% static 'favicon.png' %}">
  <link href="{% static 'superfish/superfish.css' %}" rel="stylesheet" media="screen">
  <link rel="stylesheet" type = 'text/css' href="{% static 'slick/slick.css' %}">
  <link rel="stylesheet" type = 'text/css' href="{% static 'slick/slick-theme.css' %}">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script type="text/javascript" src="{% static 'jquery3.3.1.js' %}"></script>
  <script type="text/javascript" src="{% static 'superfish/superfish.js' %}"></script>
  <script type="text/javascript" src="{% static 'slick/slick.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'Cookies.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'script.js' %}"></script>
  {% block head %}
  {% endblock %}
</head>
<body>
  <main style="min-height: calc(100vh - 168px);">
  <header>
    <div class="head-text">
        <a href="/">HOTPRICE</a>
    </div>

    {% if not request.user.is_authenticated %}
    <div class="panel">
      <a href="#" class="in">
        <svg viewBox="0 0 425.2 425.2" id="key" width="25px" height="35px">
          <path d="M253.2,18.5L156.6,4.7c-4.4-0.6-11.6-1.1-16-1.1c-4.4,0-11.7,0.5-16,1.1L27.9,18.5c-4.4,0.6-7.1,4.7-6,9l44.4,177.8	c1.1,4.3,5.6,7.8,10,7.8h24v177.4l30.3,32.2h17.6l0.5-0.5v-15.7h-16.1v-16.1h16.1v-16.1h-16.1v-16.1h16.1v-16.1h-16.1V326h16.1	v-16.1h-16.1v-16.1h16.1v-16.1h-16.1v-16.1h16.1v-16.1l5.4-32.2h5.4l5.4,32.2v161l16.1-15.9V213.2h24c4.4,0,8.9-3.5,10-7.8	l44.4-177.8C260.3,23.2,257.6,19.2,253.2,18.5 M140.5,99.3c-17.3,0-31.3-14-31.3-31.2c0-17.3,14-31.2,31.3-31.2	c17.3,0,31.3,14,31.3,31.2C171.8,85.3,157.8,99.3,140.5,99.3"></path>
          <path d="M168.3,213.2h-5.4l-5.4,32.2v16.1h-16.1v16.1h16.1v16.1h0v0h-16.1v16.1h16.1V326h0l0,0h-16.1v16.1h16.1v16.1h0l0,0h-16.1	v16.1h16.1h0v16.1h-16.1v16.1h16.1h0v15.7h0v0.5l16.1-16.4v-161L168.3,213.2"></path>
          <path d="M148.6 406.6L148.6 406.6l0 15.7h0V406.6M148.6 374.4L148.6 374.4l0 16.1h-16.1v16.1h0v-16.1h16.1V374.4M132.5 358.3L132.5 358.3l0 16.1h0V358.3M132.5  326L132.5 326l0 16.1h16.1v16.1h0v-16.1h-16.1V326M132.5 293.8L132.5 293.8l0 16.1h16.1V326h0v-16.1h-16.1V293.8M154 213.2L154 213.2l-5.4 32.2v16.1h-16.1v16.1h16.1v16.1h0v-16.1h-16.1v-16.1h16.1v-16.1L154 213.2M159.4 213.2L159.4 213.2l5.3 32.2v161-161L159.4 213.2M306.6 201.3l21.6-14.4c3.7-2.5 5.5-7.9 4-12.1L283.1 38.3l-40 173.3c-3.8 15.2-13.9 26.5-30 27.3v16.7 2.6c3 2.1 6.6 2.3 9.9.1l17.4-12.2 97.9 149.6 44.5 8.9 14.5-9.8 7.6-43.9L306.6 201.3z"></path>
        </svg>
        <span>In</span>
      </a>
    </div>
    {% else %}
    <div class="panel">
      <a href="{% url 'favorites:favorites_list' %}" class="favorites">
        <svg id="svg-favorites" viewBox="0 0 26 22" width="20px" height="23px">
          <path type="path" fill-rule="nonzero" stoke-width="10" stoke="#a33" d="M13.049,21.985c-0.029,0-0.067,0-0.098,0c-0.12,0-0.234-0.02-0.341-0.056 c-0.219-0.047-0.422-0.128-0.604-0.24C5.15,17.512,1.034,11.905,1,6.691C0.995,4.794,1.621,3.095,2.763,1.902 c1.174-1.24,2.881-1.951,4.845-1.916c2.559-0.015,4.335,1.622,5.393,3.096c1.06-1.474,2.792-3.101,5.407-3.095 c1.982,0.014,3.653,0.675,4.832,1.917C24.38,3.096,25.005,4.795,25,6.688c-0.034,5.216-4.15,10.824-11.013,15.005 c-0.18,0.112-0.386,0.192-0.608,0.238C13.275,21.966,13.164,21.985,13.049,21.985z M12.777,19.824L12.777,19.824L12.777,19.824z M7.596,2.164c-1.362,0-2.524,0.444-3.288,1.251c-0.765,0.798-1.164,1.926-1.16,3.267c0.022,3.412,2.627,8.633,9.86,13.077 c7.208-4.423,9.823-9.658,9.845-13.08c0.003-1.337-0.396-2.465-1.156-3.258c-0.001-0.002-0.002-0.003-0.004-0.005 c-0.763-0.807-1.925-1.251-3.273-1.251c-0.017,0.001-0.04,0-0.06,0c-2.303,0-3.713,2.119-4.366,3.435 c-0.16,0.405-0.543,0.704-0.989,0.705c-0.001,0-0.003,0-0.004,0c-0.511,0-0.94-0.335-1.048-0.814 c-0.675-1.32-2.069-3.327-4.297-3.327C7.637,2.163,7.616,2.164,7.596,2.164z">
          </path>
        </svg>
      </a>
      <p class="count-favorites">({{ request.user.favorites.count }})</p>
      <a href="{% url 'users:sign_out' %}" class="out">
        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="25px" height="35px"
          viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
          <g>
          	<g>
          		<g>
          			<path d="M256,181.333c0,5.888,4.779,10.667,10.667,10.667h106.667c5.888,0,10.667-4.779,10.667-10.667v-128
          				C384,23.936,360.064,0,330.667,0H182.976c-5.056,0-9.429,3.563-10.453,8.512c-1.024,4.949,1.6,9.963,6.251,11.947l36.352,15.573
          				C239.957,46.699,256,71.019,256,98.005V181.333z"/>
          			<path d="M206.741,55.659L85.568,3.712C79.808,1.259,73.685,0,67.392,0C42.005,0,21.333,20.672,21.333,46.059v367.936
          				c0,18.453,10.965,35.072,27.925,42.347l121.173,51.947c5.76,2.453,11.883,3.712,18.176,3.712
          				c25.387,0,46.059-20.672,46.059-46.059V98.005C234.667,79.552,223.701,62.933,206.741,55.659z M192,288
          				c0,5.888-4.779,10.667-10.667,10.667s-10.667-4.779-10.667-10.667v-42.667c0-5.888,4.779-10.667,10.667-10.667
          				S192,239.445,192,245.333V288z"/>
          			<path d="M373.333,256H266.667c-5.888,0-10.667,4.779-10.667,10.667v170.667c0,5.888,4.779,10.667,10.667,10.667h64
          				C360.064,448,384,424.064,384,394.667v-128C384,260.779,379.221,256,373.333,256z"/>
          			<path d="M490.091,221.184c-0.107-0.384-0.085-0.811-0.235-1.195c-0.555-1.387-1.387-2.603-2.453-3.627l-63.872-63.872
          				c-4.16-4.16-10.923-4.16-15.083,0c-4.16,4.16-4.16,10.923,0,15.083l45.76,45.76H266.667c-5.888,0-10.667,4.779-10.667,10.667
          				s4.779,10.667,10.667,10.667h187.584l-45.803,45.803c-4.16,4.16-4.16,10.923,0,15.083c2.091,2.069,4.821,3.115,7.552,3.115
          				c2.731,0,5.461-1.045,7.531-3.093l64-64c0.299-0.299,0.405-0.683,0.661-0.981c0.619-0.768,1.259-1.557,1.643-2.496
          				c0.384-0.917,0.469-1.899,0.576-2.859c0.064-0.427,0.256-0.811,0.256-1.237C490.667,222.997,490.347,222.101,490.091,221.184z"/>
          		</g>
          	</g>
          </g>
        </svg>
      </a>
    </div>
    {% endif %}

    {% block header %}
    {% endblock %}

  </header>
  <article class="main main-container">
    {% block content %}
    {% endblock %}

    {% if not request.user.is_authenticated %}
      {% include "users/pop_up_login_register.html" %}
    {% endif %}
  </article>
  </main>
  <footer>
    {% block footer %}
    {% endblock %}
    <div class="text-center text-created">
      <p>This site creating in training frames</p>
      <p>by Alexandr Korobchuk</p>
    </div>
  </footer>
</body>
</html>