aggregator_site/aggregator_site/urls.py
from django.contrib import admin
from django.urls import path, include
from favorites.urls import router as favorites_router
from categories.urls import router as categories_router
from rest_framework_swagger.views import get_swagger_view


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("products.urls")),
    path("user/", include("users.urls")),
    path("favorites/", include("favorites.urls")),
    path("categories/", include("categories.urls")),
    path("spiders/", include("spiders.urls")),

    path('accounts/', include('allauth.urls')),

    path("api/favorites/", include(favorites_router.urls)),
    path("api/categories/", include(categories_router.urls)),
    path("api/products/", include("products.api_urls")),
    path("api/spiders/", include("spiders.api_urls")),
    path("api/", include("users.register_authorization_urls")),

    path('swagger/', get_swagger_view(title='API')),
]

admin.site.site_header = "Admin"

aggregator_site/spiders/urls.py
from django.urls import path

from rest_framework.routers import DefaultRouter

from . import views

app_name = "spiders"

urlpatterns = [
    path("", views.SpidersView.as_view(), name="spiders"),
]

aggregator_site/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("sign-in/", views.UserAuthentication.as_view(), name="sign_in"),
    path("sign-out/", views.UserLogout.as_view(), name="sign_out"),
    path("registration/", views.UserCreate.as_view(), name="registration"),
    path("verify/<str:uuid>/", views.VerifyEmail.as_view(), name="verify_email"),
]

aggregator_site/spiders/models.py
import requests
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, URLValidator
from django.core.exceptions import ValidationError

from spiders.services import check_spider_on_scrapyd


class Spider(models.Model):
    day_of_week_arr = ["-1", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
    day_of_week_choices = [(num, day) for num, day in zip(range(-1, 7), day_of_week_arr)]

    name = models.CharField(max_length=60, blank=False, unique=True)
    start_url = models.CharField(max_length=255, blank=False, validators=(URLValidator(schemes=['http', 'https']), ))
    activate = models.BooleanField(default=False)
    jobid = models.CharField(blank=True, max_length=60)
    minute = models.SmallIntegerField(default=-1, validators=(MinValueValidator(-1), MaxValueValidator(59)))
    hour = models.SmallIntegerField(choices=[(i, str(i)) for i in range(-1, 24)], default=-1,
                                    validators=(MinValueValidator(-1), MaxValueValidator(23)))
    day_of_week = models.SmallIntegerField(choices=day_of_week_choices, default=-1,
                                           validators=(MinValueValidator(-1), MaxValueValidator(6)))
    day_of_month = models.SmallIntegerField(choices=[(i, str(i)) for i in range(-1, 31) if i != 0], default=-1,
                                            validators=(MinValueValidator(-1), MaxValueValidator(31)))

    class Meta:
        ordering = ("-name", )

    def __str__(self):
        text = self.name
        for attr_name in ("minute", "hour", "day_of_week", "day_of_month"):
            attr = getattr(self, attr_name)
            text += f" | {attr_name}: {attr}" if attr != -1 else ""
        return text

    def clean(self):
        error = check_spider_on_scrapyd(self)
        if error:
            raise ValidationError(error)
        elif self.minute == -1 and self.hour == -1 and self.day_of_week == -1 and self.day_of_month == -1:
            raise ValidationError("You must choose the least one of parameneter for run spider")

    @property
    def spider_exist(self):
        spider_name = self.name
        url = "http://localhost:6800/listspiders.json?project=scraping"
        response = requests.get(url).json()
        if (response["status"] == "error") or (spider_name not in response["spiders"]):
            return False
        return True

aggregator_site/spiders/views.py
import requests
import logging
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.mixins import PermissionRequiredMixin
from .models import Spider
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django_celery_beat.models import PeriodicTask


log_file = logging.getLogger("file")
log_to_email = logging.getLogger("send_on_mail")


class SpidersView(PermissionRequiredMixin, View):
    """
        models.PeriodicTask.name == models.Spider.name == scraping.spiders.some_spider.name
    """
    permission_required = 'is_superuser'

    def get(self, request):
        spiders = Spider.objects.all()
        return render(request, "spiders/spiders_list.html", {"spiders": spiders})

    def post(self, request):
        urls = request.POST.get("urls")
        spider_name = request.POST.get("spider_name")

        action = request.POST.get("action")
        spiders = Spider.objects.all()

        handler = {
            "start": self.start,
            "cancel": self.cancel,
            "disable": self.disable,
            "enable": self.enable,
        }.get(action)

        status, error = handler(urls, spider_name)

        return render(request, "spiders/spiders_list.html", {"spiders": spiders,
                                                             "current_spider": {"name": spider_name,
                                                                                "status": status,
                                                                                "error": error}})

    def disable(self, urls, spider_name):
        periodic_task = PeriodicTask.objects.get(name=spider_name)
        periodic_task.enabled = False
        periodic_task.save()
        log_to_email.warning(f"PeriodicTask of Spider - {spider_name} was disabled")
        return "ok", ""

    def enable(self, urls, spider_name):
        periodic_task = PeriodicTask.objects.get(name=spider_name)
        periodic_task.enabled = True
        periodic_task.save()
        return "ok", ""

    def cancel(self, urls, spider_name):
        jobid = Spider.objects.get(name=spider_name).jobid
        status = "ok"
        if jobid:
            data = {"job": jobid, "project": "scraping"}
            response = requests.post("http://localhost:6800/cancel.json", data=data).json()
            status = response["status"]
            Spider.objects.filter(name=spider_name).update(activate=False)
            log_to_email.warning(f"Spider - {spider_name} with job_id - {jobid} was canceled")
        return status, ""

    def start(self, urls, spider_name):
        is_valid, error = self.urls_validate(urls)
        status = "ok"
        if not error:
            data = {"project": "scraping", "spider": spider_name, "urls": urls}
            response = requests.post("http://localhost:6800/schedule.json", data=data).json()
            Spider.objects.filter(name=spider_name).update(jobid=response["jobid"], activate=True)
            status = response["status"]
            log_to_email.warning(f"Spider - {spider_name} started with: {urls}")
        return status, error

    def urls_validate(self, urls):
        if urls == "":
            return "This field can't be blank"
        clean_urls = []
        for url in [i.strip() for i in urls.split(";") if i.strip() != ""]:
            try:
                URLValidator(schemes=["http", "https"])(url)
                clean_urls.append(url)
            except ValidationError as e:
                log_file.error(e)
                log_to_email.error(e)
                return False, e.message
        return True, ""

aggregator_site/spiders/templates/spiders/add_button.html
{% extends "admin/change_list.html" %}

{% block object-tools-items %}
{{ block.super }}
<li>
  <a href="{% url 'spiders:spiders' %}">Spiders Configuration</a>
</li>
{% endblock %}

aggregator_site/spiders/templates/spiders/spiders_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Spiders</title>
  <style>
    .spider_block {
      border: 2px solid black;
      width: 400px;
      margin-bottom: 30px;
      padding: 15px;
    }
    .buttons {
      display: flex;
    }
    .buttons>input {
      margin: 20px 0;
    }
    .buttons>input:first-child {
      margin-right: 20px;
    }
    form>input:nth-child(2) {
      width: 350px;
    }
    h4 {
      display: inline-block;
    }
    .status {
      color: green;
    }
    .error {
      color: red;
    }
  </style>
</head>

<body>
    <h2 class="status">{{ status }}</h2>
    <h2 class="error">{{ error }}</h2>
    {% for spider in spiders %}
      <div class="spider_block">
        <h4>Spider: {{ spider.name }} &nbsp; &nbsp; &nbsp; &nbsp;</h4>
        <span>is activate: {{ spider.activate }}</span>
        {% if current_spider.name == spider.name %}
          <div class="status">{{ current_spider.status }}</div>
          <div class="error">{{ current_spider.error }}</div>
        {% endif %}
        <p style="font-size: 14px">You can input multi url, just split it with ";"</p>

        <form action="" method="POST">
          {% csrf_token %}
          <input type="hidden" name="spider_name" value="{{ spider.name }}">
          <input type="url" name="urls">

          <div class="buttons">
            <input type="submit" name="action" value="stop" {% if not spider.activate %} disabled {% endif %}>
            <input type="submit" name="action" value="start" {% if spider.activate %} disabled {% endif %}>
          </div>

          <p style="font-size: 14px; margin: 0;">Disble or Enable Main Periodic Task</p>

          <div class="buttons">
            <input type="submit" name="action" value="disable">
            <input type="submit" name="action" value="enable">
          </div>

        </form>

      </div>
    {% endfor %}
</body>

</html>