aggregator_site/aggregator_site/urls.py
from django.contrib import admin
from django.urls import path, include
from favorites.urls import router as favorites_router
from categories.urls import router as categories_router
from rest_framework_swagger.views import get_swagger_view


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("products.urls")),
    path("user/", include("users.urls")),
    path("favorites/", include("favorites.urls")),
    path("categories/", include("categories.urls")),
    path("spiders/", include("spiders.urls")),

    path('accounts/', include('allauth.urls')),

    path("api/favorites/", include(favorites_router.urls)),
    path("api/categories/", include(categories_router.urls)),
    path("api/products/", include("products.api_urls")),
    path("api/spiders/", include("spiders.api_urls")),
    path("api/", include("users.register_authorization_urls")),

    path('swagger/', get_swagger_view(title='API')),
]

admin.site.site_header = "Admin"

aggregator_site/products/urls.py
from django.urls import path, include
from . import views, api_views

app_name = "products"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("category/<int:category_id>", views.ProductsFromCategory.as_view(), name="products_from_category"),
    path("detail/<int:pk>/", views.ProductDetail.as_view(), name="product_detail"),
    path("search/", views.Search.as_view(), name="search"),
    path("search/autocomplete/", views.autocomplete),

    # path("api/reviews/", api_views.ReviewListCreate.as_view(), name="review"),
    path("api/ratings/", api_views.RatingListCreate.as_view(), name="rating"),
]

aggregator_site/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("sign-in/", views.UserAuthentication.as_view(), name="sign_in"),
    path("sign-out/", views.UserLogout.as_view(), name="sign_out"),
    path("registration/", views.UserCreate.as_view(), name="registration"),
    path("verify/<str:uuid>/", views.VerifyEmail.as_view(), name="verify_email"),
]

aggregator_site/products/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from mptt.models import TreeForeignKey
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.db.models import Avg


class Store(models.Model):
    name = models.CharField(max_length=40)


class SourceProduct(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    price = models.DecimalField(decimal_places=2, max_digits=16)
    rating = models.DecimalField(decimal_places=1, max_digits=3)
    store = models.ForeignKey(Store, on_delete=models.SET_NULL, null=True)
    url_in_store = models.SlugField(max_length=255)
    description = models.TextField(max_length=2000)
    product = models.ForeignKey("Product", on_delete=models.CASCADE, related_name="source_products")

    def __str__(self):
        return f"{self.name} | price: {self.price} | {self.store.name}"


class ReviewSourceProduct(models.Model):
    source_product = models.ForeignKey(SourceProduct, on_delete=models.CASCADE, related_name="reviews_source")
    username = models.CharField(max_length=60)
    text = models.TextField(max_length=1000)
    advantages = models.TextField(max_length=255, blank=True)
    disadvantages = models.TextField(max_length=255, blank=True)
    date = models.CharField(max_length=30, blank=True)


class Product(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    category = TreeForeignKey("categories.Category", on_delete=models.CASCADE, related_name="products")
    features = models.ManyToManyField("Feature", related_name="products")
    average_price = models.ManyToManyField("AveragePrice", related_name="products")
    description = models.TextField(max_length=2000)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)
    # slug = models.SlugField(max_length=150, unique=True, blank=True, verbose_name="url")
    #
    # def save(self):
    #     self.slug = self.gen_slug(self.name)
    #     super().save()

    class Meta:
        ordering = ("-name", )

    def __str__(self):
        return f"Product {self.name} | in category {self.category.get_full_path()}"

    @property
    def rating(self):
        rating = self.rating_products.aggregate(Avg("rating"))["rating__avg"]
        if rating is None:
            return 0
        return rating


class RatingProduct(models.Model):
    rating = models.IntegerField(validators=(MinValueValidator(1), MaxValueValidator(5)))
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="rating_products")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="rating_products")


class ReviewProduct(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="reviews")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="reviews")
    text = models.TextField(max_length=1000)
    advantages = models.TextField(max_length=255, blank=True)
    disadvantages = models.TextField(max_length=255, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"Username - {self.user.username} | review {self.text[:15]}..."


class AveragePrice(models.Model):
    price = models.DecimalField(decimal_places=2, max_digits=18)
    date = models.DateTimeField(auto_now_add=True)


class Feature(models.Model):
    feature = models.CharField(max_length=60, db_index=True, blank=True)
    value = models.CharField(max_length=500)


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    name = models.CharField(max_length=255)

aggregator_site/products/forms.py
from django import forms
from .models import ReviewProduct
from django.forms import ModelForm
from django_starfield import Stars


class AddRatingForm(forms.Form):
    rating = forms.IntegerField(widget=Stars, label="")


class ReviewForm(ModelForm):
    class Meta:
        model = ReviewProduct
        fields = ("user", "product", "text", "advantages", "disadvantages")

aggregator_site/products/views.py
import json
import logging

from django.http import HttpResponse
from django.shortcuts import render, reverse
from django.views.generic import View, TemplateView, DetailView, CreateView, ListView
from django.shortcuts import render
from categories.models import Category
from haystack.backends import SQ
from haystack.forms import ModelSearchForm
from haystack.inputs import AutoQuery
from haystack.query import SearchQuerySet

from .models import Product, SourceProduct, RatingProduct
from .forms import ReviewForm, AddRatingForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from .utils import get_min_max_price, get_images, paginator, pretty_price, SearchAndProductsFromCategoryMixin
from haystack.generic_views import SearchView
from django.views import View


log = logging.getLogger("file")


class CustomModelSearchFrom(ModelSearchForm):
    def search(self):
        if not self.is_valid():
            return self.no_query_found()

        if not self.cleaned_data.get('q'):
            return self.no_query_found()

        q = self.cleaned_data['q']
        sqs = self.searchqueryset.filter(SQ(name__contains=AutoQuery(q)) |
                                         SQ(category=AutoQuery(q)) |
                                         SQ(description=AutoQuery(q)) |
                                         SQ(categories_ancestors=AutoQuery(q)))

        if self.load_all:
            sqs = sqs.load_all()
        return [result for result in sqs.highlight() if result.score > 0.03]


def autocomplete(request):
    q = request.GET.get('q', '')
    if q:
        sqs = SearchQuerySet().autocomplete(content_auto=q)[:5]

        suggestions = [{"name": result.name, "id": result.pk, "score": result.score} for result in sqs]
        for i in range(len(suggestions) - 1):
            for j in range(len(suggestions) - 1):
                if suggestions[j]["name"] > suggestions[j + 1]["name"]:
                    tmp = suggestions[j]
                    suggestions[j] = suggestions[j + 1]
                    suggestions[j + 1] = tmp
    else:
        suggestions = ""
    the_data = json.dumps({
        'results': suggestions
    })

    return HttpResponse(the_data, content_type='application/json')


class Search(SearchView):
    template_name = "products/index.html"
    paginate_by = 25
    form_class = CustomModelSearchFrom

    def get_context_data(self, *args, **kwargs):

        context = super(Search, self).get_context_data(*args, **kwargs)
        q = self.request.GET["q"]
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = self.request.META.get('REMOTE_ADDR')
        user = self.request.user
        if user:
            username = user.username
        else:
            username = "User"

        log.info(f"{username} with ip - {ip}, search - '{q}'")

        search_query_set = context["object_list"]
        products = [Product.objects.get(id=prod.pk) for prod in search_query_set]

        page = context["page_obj"]
        context["is_paginator"] = context["is_paginated"]
        context["categories"] = Category.objects.filter(parent=None)
        paginator = context["paginator"]

        context["next_url"] = f"?page={page.number+1}&q={self.request.GET['q']}" \
                              if page.number + 1 <= paginator.num_pages else ""
        context["prev_url"] = f"?page={page.number-1}&q={self.request.GET['q']}" if page.number - 1 > 0 else ""

        images = get_images(products)
        prices = get_min_max_price(products)
        pretty_prices = []

        for low_price, hight_price in prices:
            pretty_prices.append((pretty_price(low_price), pretty_price(hight_price)))
        if products:
            products = zip(products, images, pretty_prices)
        else:
            products = False
            context["not_found"] = True
        context["page"] = page
        context["products"] = products

        return context


class Index(ListView):
    queryset = Category.objects.filter(parent=None)
    template_name = "products/index.html"
    context_object_name = "categories"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context


class ProductsFromCategory(SearchAndProductsFromCategoryMixin, ListView):
    template_name = "products/index.html"
    view_name = "ProductsFromCategory"


class ProductDetail(DetailView):
    template_name = "products/product_detail.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = context["product"]

        breadcrumb = Category.objects.get(name=product.category.name, parent=product.category.parent).get_ancestors(include_self=True)

        source_products = SourceProduct.objects.filter(product=product)
        context["images"] = get_images(product)
        context["price"] = get_min_max_price(product)

        pretty_price_products = []
        for source_product in source_products:
            pretty_price_products.append(pretty_price(source_product.price))
        source_products_n_pretty_price = zip(source_products, pretty_price_products)
        if self.request.user.is_authenticated:
            if not RatingProduct.objects.filter(product=product, user=self.request.user).first():
                context["rating_input"] = AddRatingForm()

        context["product"] = product
        context["breadcrumb"] = breadcrumb
        context["source_products_n_pretty_price"] = source_products_n_pretty_price
        return context

aggregator_site/products/templates/products/average_price_graph.html
<script type="text/javascript">

window.onload = function() {
  let x_data = [];
  let y_data = [];
{% for avg_price in product.average_price.all %}
  // console.log("{{ avg_price.price }}");
  // console.log("{{ avg_price.date }}");
  y_data.push("{{ avg_price.price }}");
  x_data.push("{{ avg_price.date }}".split(",")[0]);
{% endfor %}
layout = {
  width: 350,
  height: 250,
  margin: {
    t: 10,
  },
  // paper_bgcolor: '#7f7f7f',
  plot_bgcolor: '#551a8a',

  yaxis: {
    title: "Price",
    showgrid: false
  },

  xaxis: {
    ticks: 'outside',
    showgrid: false,
    zeroline: false,
    tick0: 0,
    dtick: 0.25,
    ticklen: 8,
    tickwidth: 4,
    tickcolor: '#000'
  },
};

Plotly.plot("chart_1", [{
  y:y_data,
  x:x_data,
  type: "line",
}], layout, {displayModeBar: false});

}
</script>

aggregator_site/products/templates/products/cards.html
{% if not filters %}
  <div class="card-container" style="width: 976px;">
{% else %}
  <div class="card-container">
{% endif %}
  {% for product, images, prices in products %}
  {% if not filters %}
    <div class="card" style="margin: 12px;">
  {% else %}
    <div class="card">
  {% endif %}
      <p class="title"><a href="{% url 'products:product_detail' product.id %}">{{ product.name|truncatechars:50 }}</a></p>
      <div class="images">
      {% for url in images %}
        <img src="{{ url }}" alt="image">
      {% endfor %}
      </div>
      <div class="prices">
        <span>Price: {{ prices.0 }}&ndash;{{ prices.1 }} UAH</span>
      </div>
      <a href="{% url 'products:product_detail' product.id %}#all-offers" class="all-offers">all offers ({{ product.source_products.count }})</a>
      <div class="button-compare">
        <a href="{% url 'products:product_detail' product.id %}">Compare prices</a>
      </div>
      {% if request.user.is_authenticated %}
        <div class="add-to-bookmarks">
          <svg id="svg-like" viewBox="0 0 26 22" width="20px" height="23px">
            <path type="path" fill-rule="nonzero" stoke-width="10" stoke="#a33" d="M13.049,21.985c-0.029,0-0.067,0-0.098,0c-0.12,0-0.234-0.02-0.341-0.056 c-0.219-0.047-0.422-0.128-0.604-0.24C5.15,17.512,1.034,11.905,1,6.691C0.995,4.794,1.621,3.095,2.763,1.902 c1.174-1.24,2.881-1.951,4.845-1.916c2.559-0.015,4.335,1.622,5.393,3.096c1.06-1.474,2.792-3.101,5.407-3.095 c1.982,0.014,3.653,0.675,4.832,1.917C24.38,3.096,25.005,4.795,25,6.688c-0.034,5.216-4.15,10.824-11.013,15.005 c-0.18,0.112-0.386,0.192-0.608,0.238C13.275,21.966,13.164,21.985,13.049,21.985z M12.777,19.824L12.777,19.824L12.777,19.824z M7.596,2.164c-1.362,0-2.524,0.444-3.288,1.251c-0.765,0.798-1.164,1.926-1.16,3.267c0.022,3.412,2.627,8.633,9.86,13.077 c7.208-4.423,9.823-9.658,9.845-13.08c0.003-1.337-0.396-2.465-1.156-3.258c-0.001-0.002-0.002-0.003-0.004-0.005 c-0.763-0.807-1.925-1.251-3.273-1.251c-0.017,0.001-0.04,0-0.06,0c-2.303,0-3.713,2.119-4.366,3.435 c-0.16,0.405-0.543,0.704-0.989,0.705c-0.001,0-0.003,0-0.004,0c-0.511,0-0.94-0.335-1.048-0.814 c-0.675-1.32-2.069-3.327-4.297-3.327C7.637,2.163,7.616,2.164,7.596,2.164z">
            </path>
          </svg>
          <span class="add-to-favorites" id="{{ product.id }}">Add to bookmarks</span>
        </div>
      {% endif %}
    </div>
  {% endfor %}
</div>

aggregator_site/products/templates/products/index.html
{% extends "base.html" %}

{% block head %}
<script type="text/javascript">
    // In a perfect world, this would be its own library file that got included
    // on the page and only the ``$(document).ready(...)`` below would be present.
    // But this is an example.
    var Autocomplete = function(options) {
      this.form_selector = options.form_selector
      this.url = options.url || '/search/autocomplete/'
      this.delay = parseInt(options.delay || 300)
      this.minimum_length = parseInt(options.minimum_length || 3)
      this.form_elem = null
      this.query_box = null
    }

    Autocomplete.prototype.setup = function() {
      var self = this

      this.form_elem = $(this.form_selector)
      this.query_box = this.form_elem.find('input[name=q]')

      // Watch the input box.
      this.query_box.on('keyup', function() {
        var query = self.query_box.val()
          console.log("HEERRE: ", query);

        if(query.length < self.minimum_length) {
          return false
        }

        self.fetch(query)
      })

      // On selecting a result, populate the search field.
      this.form_elem.on('click', '.ac-result', function(ev) {
        self.query_box.val($(this).text())
        $('.ac-results').remove()
        return false
      })
    }

    Autocomplete.prototype.fetch = function(query) {
      var self = this;
      if (query.length >= this.minimum_length) {

          $.ajax({
              url: this.url
              , data: {
                  'q': query
              }
              , success: function (data) {
                  self.show_results(data);
              }
          })
      }
      else self.show_results("");
    }

    Autocomplete.prototype.show_results = function(data) {
      // Remove any existing results.
      $('.ac-results').remove()

      var results = data.results || []
      var results_wrapper = $('<div class="ac-results"></div>')
      var base_elem = $('<div class="result-wrapper"><a href="#" class="ac-result"></a></div>')

      if(results.length > 0) {
        for(var res_offset in results) {
          var elem = base_elem.clone();
          let href = "/detail/" + results[res_offset]["id"];
          elem.find(".ac-result").attr("href", href);
          // Don't use .html(...) here, as you open yourself to XSS.
          // Really, you should use some form of templating.
          elem.find('.ac-result').text(results[res_offset]["name"]);
          console.log(results[res_offset]);
          results_wrapper.append(elem);
          let suggest = document.getElementById("suggestion");
          suggest.innerHTML = results_wrapper.prop('outerHTML');
        }
      }
      else {
        var elem = base_elem.clone()
        elem.text("No results found.")
        results_wrapper.append(elem)
      }

      this.query_box.after(results_wrapper)
    }

    $(document).ready(function() {
      window.autocomplete = new Autocomplete({
        form_selector: '.autocomplete-me',
        minimum_length: 3
      })
      window.autocomplete.setup()

      kinput = document.getElementById("search");
      kinput.onkeyup = presskeyHandle;

      function presskeyHandle(e) {
          window.autocomplete.fetch(kinput.value);
        }
    })


  </script>
{% endblock %}

{% block header %}
<div class="search-form">
  <form action="{% url 'products:search' %}" method="GET">
      <input type="text" name="q" id="search" class="autocomplete-me" autocomplete="off">
      <button type="submit">GO</button>
      <div id="suggestion"></div>
  </form>
</div>

<div class="categories">
  <ul class="sf-menu">
    {% for category in categories %}
      {% include "categories/category.html" with category=category childrens=category.get_descendants %}
    {% endfor %}
  </ul>
</div>
{% endblock %}

{% block content %}
    {% if breadcrumb %}
      {% include "categories/breadcrumb.html" %}
    {% endif %}

    <div class="filters-products">
        {% block filters %}
        {% endblock %}
        {% if products %}
          {% include "products/cards.html" with products=products images=images %}
        {% elif not_found %}
          <div class="card-container">
            <p class="not-found-products">NOT FOUND :(</p>
          </div>
        {% else %}
          <p class="text-choose-category">Choose category or type in search-form</p>
        {% endif %}
    </div>

    <!--Paginator -->
    {% if is_paginator %}
      <nav aria-label="..." class="paginator">
        <ul class="pagination" style="padding-left: 40px;">
          <li class="page-item {% if not prev_url %} disabled {% endif %}">
            <a class="page-link" href="{{ prev_url }}" tabindex="-1">Предыдущая</a>
          </li>

          {% for n in page.paginator.page_range %}
            {% if page.number == n %}
              <li class="page-item active">
                <a class="page-link" href="?page={{ n }}&q={{ request.GET.q }}">{{ n }}<span class="sr-only">(current)</span></a>
              </li>

            {% elif n > page.number|add:-3 and n < page.number|add:3 %}
              <li class="page-item"><a class="page-link" href="?page={{ n }}&q={{ request.GET.q }}">{{ n }}</a></li>
            {% endif %}
          {% endfor %}

          <li class="page-item {% if not next_url %} disabled {% endif %}">
            <a class="page-link" href="{{ next_url }}">Следующая</a>
          </li>
        </ul>
      </nav>
    {% endif %}
  <!-- end Paginator  -->
  <form action="" method="POST">{% csrf_token %}</form>
{% endblock %}

aggregator_site/products/templates/products/product_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
  <script type="text/javascript" src="{% static 'plotly.min.js' %}"></script>
  {% include 'products/average_price_graph.html' with product=product %}
{% endblock %}

{% block content %}
  {% include "categories/breadcrumb.html" %}
  <div class="product">
    <p class="product_name">{{ product.name }}</p>
    <div class="container">
      <div>
        <div class="images" >
          {% for url in images %}
            <img src="{{ url }}" alt="image">
          {% endfor %}
        </div>
        <p class="price">Price: {{ price.0 }}&ndash;{{ price.1 }} UAH</p>
        <p class="text-muted text-center" style="margin-top: 5px;" id="rating" denominator={{ product.rating_products.count }}>Rating: <span>{{ product.rating }}</span></p>
        {% if rating_input %}
          <form action="{% url 'products:rating' %}" method="POST" id="form-rating">
            {% csrf_token %}
            <div class="text-center">
              {{ rating_input }}
            </div>
          </form>
        {% endif %}
      </div>

      <div class="chart-container">
        <p class="text-center">Average Prices</p>
        <div id="chart_1">

        </div>
      </div>
    </div>

    {% if product.description|length > 10 %}
      <div class="description">
        <p class="text-description">Description:</p>
        {{ product.description|safe }}
      </div>
    {% endif %}

    <div class="container">
      <div class="features">
        <p class="text-features">Features</p>
          <table>
            {% for feature in product.features.all %}
              <tr>
                <td class="feature_name">{{ feature.feature }}</td>
                <td class="value_name" >{{ feature.value }}</td>
              </tr>
            {% endfor %}
          </table>
      </div>

      <div class="reviews-offers">
        <div>
          <a href="" id="offers" class="reviews-offers-activate">Offers</a>
          <a href="" id=reviews>Reviews</a>
        </div>

        {% for source_product, pretty_price in source_products_n_pretty_price %}
        <div class="offer">
          <a href="{{ source_product.url_in_store }}">{{ source_product.store.name }}</a>
          <span>{{ pretty_price }} UAH</span>
          {% if source_product.reviews_source.exists %}
            <a href="{{ source_product.store.name }}" class="btn-source-reviews activate ">Reviews</a>
          {% else %}
            <a class="btn-source-reviews non-activated">Reviews</a>
          {% endif %}
        </div>

        <div class="source-review-container">
          {% for review_source in source_product.reviews_source.all %}
            <div class="source-review {{ source_product.store.name }}" style="display: none;">
              <p class="name">Name: {{ review_source.user }}</p>
              <p class="advantages">Advantages: {{ review_source.advantages }}</p>
              <p class="disadvantages">Disadvantages: {{ review_source.disadvantages }}</p>
              <p class="text">{{ review_source.text }}</p>
              <p class="date">{{ review_source.date }}</p>
            </div>
          {% endfor %}
          </div>
        {% endfor %}

        <div class="reviews" style="display: none;">
          {% with product_reviews=product.reviews.all  %}
          {% if not product_reviews %}
            <p class="text-muted" style="text-align: center; font-size: 28px; margin-top: 20px;">None reviews :(</p>
          {% endif %}
          {% for review in product_reviews %}
            <div class="review">
              <p class="name">Name: {{ review.user.username }}</p>
              <p class="advantages">Advantages: {{ review.advantages }}</p>
              <p class="disadvantages">Disadvantages: {{ review.disadvantages }}</p>
              <p class="text">{{ review.text|linebreaks }}</p>
              <p class="date">{{ review.date }}</p>
            </div>
          {% endfor %}
          {% endwith %}

          {% if request.user.is_authenticated %}
            <form action="{% url 'review-list' %}" method="POST" id="send-review">
              {% csrf_token %}

              <input type="hidden" value="{{ product.id }}" name="product" id="review-product">
              <input type="hidden" value={{ request.user.username }} name="username" id="review-username">
              <div class="alert-danger errors"></div>
              <div class="form-group row">
                <label for="review-advantages" class="col-lg-2 col-form-label">Advantages:</label>
                <div class="col-lg-10">
                  <input type="text" class="form-control" placeholder="type advantages..." id="review-advantages" name="advantages"><br>
                </div>
              </div>

              <div class="form-group row">
                <label for="review-disadvantages" class="col-lg-2 col-form-label">Disadvantages:</label>
                <div class="col-lg-10">
                  <input type="text" class="form-control" placeholder="type disadvantages..." id="review-disadvantages" name="disadvantages"><br>
                </div>
              </div>

              <div class="form-group row">
                <label for="review-text" class="col-lg-2 col-form-label">Review:</label>
                <div class="col-lg-10">
                  <textarea class="form-control" resize="none" rows="5" placeholder="please type your review..." id="review-text" name="text" style="resize: none;"></textarea>
                </div>
              </div>

              <div style="margin: 20px 0" class="text-center">
                <button type="submit" class="btn btn-primary" id="btn-send-review">Enter</button>
              </div>

            </form>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}